services:
  - type: web
    name: english-bot-aria
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
